---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['instance']
      group_wait: 10m
      group_interval: 10s
      repeat_interval: 10m  
      receiver: 'web.hook.prometheusalert'
    receivers:
    - name: 'web.hook.prometheusalert'
      webhook_configs:
      - url: 'http://prometheus-alert-center:8080/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=b534676b6a4914b531d217b799524ff4d73a730e81c169d5afa3f33b734bbb51'